CREATE DATABASE DB_SIMPLE_BANK;
USE DB_SIMPLE_BANK;
GO

-- FUNÇÃO (ENVIAR, RECEBER E ATUALIZAR)
-- CADASTRAR O USUÁRIO (ADMIN SE CADASTRA E CADASTRA O CLIENTE)
-- ADMIN ATUALIZA AS INFORMACOES DO CLIENTE
-- VISUALIZAR O USUÁRIO (PERFIL)
CREATE TABLE TB_USUARIO (
	ID INT PRIMARY KEY IDENTITY(1,1), -- GERADOR DE ID
	NOME VARCHAR(100) NOT NULL,
	CPF VARCHAR(14) NOT NULL,
	-- VAI PRECISAR DE RG?
	TELEFONE VARCHAR(15),
	EMAIL VARCHAR(100) NOT NULL,
	-- NAO PRECISA SER OBRIGATÓRIO, POR CAUSA DO ADMIN
	CEP VARCHAR(9),
	RUA VARCHAR(50),
	BAIRRO VARCHAR(50), 
	NUMERO INT,
)

-- FUNÇÃO (AUTENTICAR-ENVIAR)
-- LOGAR O ADM
CREATE TABLE TB_ADMIN (
	ID INT PRIMARY KEY IDENTITY(1,1), -- GERADOR DE ID
	ID_USUARIO INT,
	SENHA VARCHAR(30) NOT NULL,
	FOREIGN KEY(ID_USUARIO) REFERENCES TB_USUARIO(ID)
)

-- FUNÇÃO (ENVIAR, AUTENTICAR, RECEBER)
-- CADASTRAR O CLIENTE
-- LOGIN DO CLIENTE
-- VISUALIZAR O USUÁRIO NO DASHBOARD/PAGINA PRINCIPAL
-- VISUALIZAR O USUÁRIO NA TELA DO ADMIN VINCULADO COM A TABELA TB_USUARIOS
CREATE TABLE TB_CONTA (
	ID INT PRIMARY KEY IDENTITY(1,1),
	ID_USUARIO INT,
	-- TIPO_CONTA NÃO PRECISA SER OBRIGATÓRIO, PORQUE VAI LOGAR O USUÁRIO
	TIPO_CONTA INT,
	AGENCIA INT NOT NULL,
	-- SALDO NÃO PRECISA SER OBRIGATÓRIO, PORQUE VAI LOGAR O USUÁRIO
	SALDO FLOAT DEFAULT 0.00,
	CONTA INT NOT NULL,
	SENHA VARCHAR(30) NOT NULL,
	FOREIGN KEY(ID_USUARIO) REFERENCES TB_USUARIO(ID)
)

-- FUNÇÃO (ENVIAR E RECEBER)
-- VISUALIZAR EXTRATO BANCÁRIO 
-- MANIPULAR O USUÁRIO AFETADO PELA A TRANSAÇÃO ALTERANDO O SALDO (SEJA DEBITAR OU CREDITAR UM VALOR) 
CREATE TABLE TB_TRANSACAO (
	ID INT PRIMARY KEY,
	ID_CONTA INT,
	TIPO_TRANSACAO INT NOT NULL, -- DEFINE BOLETO, PIX OU TED
	TIPO_OPERACAO INT NOT NULL, -- DEFINE DÉBITO OU CRÉDITO
	VALOR FLOAT NOT NULL,
	DATA_TRANSACAO DATETIME,
	FOREIGN KEY(ID_CONTA) REFERENCES TB_CONTA(ID)
)

-- FUNÇÃO (ENVIAR E RECEBER)
-- PAGAR BOLETO
-- EMITIR COMPROVANTE BOLETO
CREATE TABLE TB_BOLETO (
	ID INT PRIMARY KEY,
	ID_TRANSACAO INT,
	CODIGO_DE_BARRAS INT NOT NULL,
	BENEFICIARIO VARCHAR(100) NOT NULL,
	FOREIGN KEY(ID_TRANSACAO) REFERENCES TB_TRANSACAO(ID)
)

-- FUNÇÃO (ENVIAR E RECEBER)
-- TRANSFERIR DINHEIRO
-- EMITIR COMPROVANTE
CREATE TABLE TB_PIX (
	ID INT PRIMARY KEY,
	ID_CONTA INT,
	CHAVE_PIX VARCHAR(200) NOT NULL,
	DESCRICAO VARCHAR(200),
	FOREIGN KEY(ID_CONTA) REFERENCES TB_CONTA(ID)
)

-- FUNÇÃO (ENVIAR E RECEBER)
-- TRANSFERIR DINHEIRO
-- ADICIONAR UMA TARIFA NO VALOR QUE VAI SER PAGO
-- EMITIR COMPROVANTE
CREATE TABLE TB_TED (
	ID INT PRIMARY KEY,
	ID_TRANSACAO INT NOT NULL,
	TARIFA FLOAT NOT NULL,
	DESCRICAO VARCHAR(200),
	FOREIGN KEY(ID_TRANSACAO) REFERENCES TB_TRANSACAO(ID)
)

SELECT * FROM TB_USUARIO
SELECT * FROM TB_ADMIN
SELECT * FROM TB_CONTA
SELECT * FROM TB_TRANSACAO
SELECT * FROM TB_BOLETO
SELECT * FROM TB_PIX
SELECT * FROM TB_TED
