-- DEBITAR O SALDO DA CONTA (ID 1)
UPDATE TB_CONTA
SET SALDO = SALDO - 150.00 FROM TB_CONTA
INNER JOIN TB_PIX ON TB_CONTA.ID = TB_PIX.ID_CONTA
WHERE TB_PIX.CHAVE_PIX = 'joao@gmail.com';

-- CREDITAR O SALDO NA CONTA (ID 2)
UPDATE TB_CONTA
SET SALDO = SALDO + 150.00 FROM TB_CONTA
INNER JOIN TB_PIX ON TB_CONTA.ID = TB_PIX.ID_CONTA
WHERE TB_PIX.CHAVE_PIX = '11977501234';

-- CONSULTA DE SALDO DA CONTA DO JOÃO (ID 1)
SELECT CONTA, SALDO
FROM TB_CONTA
WHERE ID_USUARIO = 1;

-- CONSULTA DE SALDO DA CONTA DO JOÃO DE MARIA(ID 2)
SELECT CONTA, SALDO
FROM TB_CONTA
WHERE ID_USUARIO = 2;
