USE DB_SIMPLE_BANK;

-- INSERIR DADOS NA TB_TRANSACAO PARA SIMULAR UMA EMISSÃO DE EXTRATO BANCÁRIO
-- TIPO_TRANSACAO = 1 BOLETO, 2 PIX E 3 TED
-- TIPO_OPERACAO = 1 DÉBITO E 2 CRÉDITO
INSERT INTO TB_TRANSACAO (ID, ID_CONTA, TIPO_TRANSACAO, TIPO_OPERACAO, VALOR, DATA_TRANSACAO) VALUES
(1, 1, 2, 1, 150.00, GETDATE()),
(2, 2, 2, 2, 150.00, GETDATE())

-- EXTRATO COMPLETO DA CONTA DE JOÃO (ID 1)
SELECT T.ID, C.CONTA, C.AGENCIA, T.TIPO_TRANSACAO, T.TIPO_OPERACAO, T.VALOR, T.DATA_TRANSACAO
FROM TB_TRANSACAO T
JOIN TB_CONTA C ON C.ID = T.ID_CONTA
WHERE C.ID_USUARIO = 1 

-- EXTRATO COMPLETO DA CONTA DE MARIA (ID 2)
SELECT T.ID, C.CONTA, C.AGENCIA, T.TIPO_TRANSACAO, T.TIPO_OPERACAO, T.VALOR, T.DATA_TRANSACAO
FROM TB_TRANSACAO T
JOIN TB_CONTA C ON C.ID = T.ID_CONTA
WHERE C.ID_USUARIO = 2 
